on: [push]

name: Upload Release Asset

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[Release]')"
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PHP Binary
        run: wget https://jenkins.pmmp.io/job/PHP-8.1-Aggregate/lastSuccessfulBuild/artifact/PHP-8.1-Linux-x86_64.tar.gz && tar xvf PHP-8.1-Linux-x86_64.tar.gz
      - name: Download Phar Console Script
        run: wget https://raw.githubusercontent.com/pmmp/DevTools/master/src/ConsoleScript.php -O ./bin/ConsoleScript.php
      - name: Create Build Info
        id: build
        run: |
          EXTENSION_DIR=$(find "$(pwd)/bin" -name *debug-zts*)
          grep -q '^extension_dir' bin/php7/bin/php.ini && sed -i'bak' "s{^extension_dir=.*{extension_dir=\"$EXTENSION_DIR\"{" bin/php7/bin/php.ini || echo "extension_dir=\"$EXTENSION_DIR\"" >> bin/php7/bin/php.ini
          echo ::set-output name=BUILD_NAME::$(./bin/php7/bin/php -r "ini_set('display_errors', 'Off'); echo yaml_parse_file('plugin.yml')['name'];")
          echo ::set-output name=BUILD_VERSION::$(./bin/php7/bin/php -r "ini_set('display_errors', 'Off'); echo yaml_parse_file('plugin.yml')['version'];")
      - name: Create Phar
        run: |
          echo Building...
          chmod +x ./bin/ConsoleScript.php
          wget https://poggit.pmmp.io/r/189704/libasynql_dev-181.phar -O libasynql.phar
          ./bin/php7/bin/php -dphar.readonly=0 ./bin/ConsoleScript.php --make "resources,src,plugin.yml" --out WorldInventory.phar
          echo Injecting virions...
          ./bin/php7/bin/php -dphar.readonly=0 libasynql.phar WorldInventory.phar
          echo Build completed!
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build.outputs.BUILD_VERSION }}
          release_name: ${{ steps.build.outputs.BUILD_NAME }} ${{ steps.build.outputs.BUILD_VERSION }}
          draft: false
          prerelease: false
      - name: Upload Phar
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./WorldInventory.phar
          asset_name: WorldInventory.phar
          asset_content_type: application/phar